site_name: Sepettakip Kurye Entegrasyonu
use_directory_urls: true
nav:
  - 'Giriş': 'index.md'
  - 'Entegrasyon': 'integration.md'
  - 'Entegrasyon Testi': 'integration_test.md'
  - 'Entegrasyon Checklist': 'integration_checklist.md'
  - 'İletişim ve Destek': 'contact.md'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
      - python
      - go
      - javascript
      - json
      - curl
    navigation_depth: 5
    nav_style: dark

markdown_extensions:
    - smarty
    - sane_lists
